In [37]:
import numpy as np
array1 = np.array([[1, 3, 4, 4, 5]])

In [4]:
print(array1)

[1 3 4 4]


In [7]:
array2 = np.array([['dug', 'bird'], ['lion', 'tigger'], ['cat', 'dog']])

In [8]:
print(array2)

[['dug' 'bird']
 ['lion' 'tigger']
 ['cat' 'dog']]


In [31]:
animals = [['dug', 'bird', 'chicken'], ['lion', 'tigger', 'worlf'], ['cat', 'dog', 'mouse']]

In [32]:
array3 = np.array(animals)

In [33]:
print(array3)

[['dug' 'bird' 'chicken']
 ['lion' 'tigger' 'worlf']
 ['cat' 'dog' 'mouse']]


In [38]:
print(array1.shape)

(1, 5)


In [17]:
print(array2.shape)

(3, 2)


In [34]:
print(array3.shape)

(3, 3)


In [41]:
array4 = np.array([1, 3, 4, 4, 5])

In [42]:
print(array4.shape)

(5,)


## Lire un dataset avec numpy genfromtxt

In [1]:
import numpy as np
world_alcohol = np.genfromtxt('Data/world_alcohol.csv', delimiter = ',')
print(type(world_alcohol))
world_alcohol

<class 'numpy.ndarray'>


array([[      nan,       nan,       nan,       nan,       nan],
       [1.986e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.000e-01],
       ...,
       [1.986e+03,       nan,       nan,       nan, 2.540e+00],
       [1.987e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.150e+00]])

## Les types de donnée avec numpy

In [54]:
world_alcohol_dtype = world_alcohol.dtype

In [55]:
print(world_alcohol_dtype)

float64


In [63]:
print(array3.dtype)

<U7


## Afficher les données correctement

In [10]:
import numpy as np
world_alcohol = np.genfromtxt('Data/world_alcohol.csv', delimiter = ',', dtype = 'U75', skip_header = 1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Extraire une valeur depuis un tableau numpy

- Assigner le nombre de vin bu par un Ivoirien en 1985 par la variable ivoire_1985.
- Assigner le nom du pays de la 2e ligne a la variable second_country.

In [7]:
ivoire_1985 = world_alcohol[2, 4]
second_country = world_alcohol[1, 2]

In [8]:
print(ivoire_1985)

1.62


In [9]:
print(second_country)

Uruguay


### Extraire un vecteur de valeurs dans un tableau

In [33]:
animals = np.array([['dug', 'bird', 'chicken'], ['lion', 'tigger', 'worlf'], ['cat', 'dog', 'mouse']])

In [23]:
array1 = np.array([1, 3, 4, 4, 5])

In [26]:
array1[1:3]

array([3, 4])

In [34]:
animals[:,0]

array(['dug', 'lion', 'cat'], dtype='<U7')

In [37]:
animals[1,:]

array(['lion', 'tigger', 'worlf'], dtype='<U7')

In [36]:
animals[2,1:]

array(['dog', 'mouse'], dtype='<U7')

In [39]:
animals[1:,1]

array(['tigger', 'dog'], dtype='<U7')

In [40]:
countries = world_alcohol[:, 2]

In [41]:
print(countries)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [43]:
alcohol_consumption = world_alcohol[:, 4]

In [44]:
alcohol_consumption

array(['0', '0.5', '1.62', ..., '2.54', '0', '5.15'], dtype='<U75')

In [45]:
#Toutes les lignes des deux prémière colonne
first_two_column = world_alcohol[:, 0:2]
first_two_column

array([['1986', 'Western Pacific'],
       ['1986', 'Americas'],
       ['1985', 'Africa'],
       ...,
       ['1986', 'Europe'],
       ['1987', 'Western Pacific'],
       ['1986', 'Africa']], dtype='<U75')

In [54]:
for row in animals:
    for i in row:
        print(i)

dug
bird
chicken
lion
tigger
worlf
cat
dog
mouse
